### ISSUE TITLE
Messages loss

### ISSUE THREAD

**Issue by Ldoppea** [relativty/wrmhl#4]
Hi,

I just found your awesome project and now I'm trying to use it with my arduino project, but I'm not sure to use it correctly.

If i use the following arduino code : https://gist.github.com/Ldoppea/5ae1ef4f6fce579cd00238687b9e86c5
And run the Unity WRMHLread demo project,
Then the unity console will display the following : 

- value : 100
- value : 66
- value : 32
- value : 215
- value : 183
etc

A lot of messages are not received. What I would like is to receive:
- value : 100
- value : 99
- value : 98
- value : 97
- value : 96
etc

It seems like WRMHL only ensures the last message before an update to be received but does not ensure ALL messages to be received. Am I correct?

Is there a way to receive ALL messages?

Thanks

**Comment by maxime-coutte** [comment]
If the Queue Lenght value is equal to 1 WRMHL will return the latest message received before an update :)

**Comment by maxime-coutte** [comment]
If you set the Queue Lenght to 1 000 WRMHL will ensures the last 1 000 messages received before the update.

**Comment by maxime-coutte** [comment]
Does it solve your issue?

**Comment by Ldoppea** [comment]
Ok I missed that parameter. It works better now 😃 

The small difference now is that in wrmhlRead.Update() we have to call myDevice.readQueue() until it returns null.

Thanks for your fast answer 👍

**Comment by maxime-coutte** [comment]
you're welcome 😃
